### PR TITLE
Added twitch embed to stream page

### PR DESCRIPTION
**Pull request by AevumDecessus**

### CODE REVIEW

**Comment by AevumDecessus** [comment]
hmm, it's all there, but not loading, going to have to play with settings it appears

**Comment by gpmidi** [comment]
@AevumDecessus You forgot ` <script src="https://embed.twitch.tv/embed/v1.js"></script>`

**Comment by gpmidi** [comment]
Better yet, do this in `stream.html`
```
{% block head %}
<script src="https://embed.twitch.tv/embed/v1.js"></script>
{% endblock %}
```

**Comment by AevumDecessus** [comment]
heh, didn't forget it, typo
scr != src

**Review by gpmidi — APPROVED** [review]

**Pull request merged**
